kagu_homepage:
    path:     /dashboard
    defaults: { _controller: KaguBundle:Dashboard:index }

kagu_upload_image:
    path:   /upload
    defaults: { _controller: KaguBundle:Utils:uploadImage }
    options:
        expose: true

kagu_index_profil:
    path:   /profil/
    defaults: { _controller: KaguBundle:Profil:index }

kagu_index_ambiance:
    path:   /ambiance/
    defaults: { _controller: KaguBundle:Ambiance:index}
    options:
        expose: true

kagu_add_ambiance:
    path:    /ambiance/add
    defaults: { _controller: KaguBundle:Ambiance:add }

kagu_add_exe_ambiance:
    path:   /ambiance/add/exec/{data}
    defaults: { _controller: KaguBundle:Ambiance:addExec }
    options:
        expose: true

kagu_ambiance_ambiance:
    path:   /ambiance/ambiance/{ambiance}
    defaults: { _controller: KaguBundle:Ambiance:ambiance }

kagu_delete_ambiance:
    path:   /ambiance/delete/{ambiance}
    defaults: { _controller: KaguBundle:Ambiance:delete }

kagu_publish_ambiance:
    path:   /ambiance/publish/{ambiance}
    defaults: { _controller: KaguBundle:Ambiance:publish }

kagu_edit_ambiance:
    path:   /ambiance/edit/{ambiance}
    defaults: { _controller: KaguBundle:Ambiance:edit }

kagu_edit_exe_ambiance:
    path: /ambiance/edit/{ambiance}/data/{data}
    defaults: { _controller: KaguBundle:Ambiance:editExec }
    options:
        expose: true

kagu_comment_ambiance:
    path:   /ambiance/id/{id}/comment/{comment}
    defaults: { _controller: KaguBundle:Ambiance:addComment }
    options:
        expose: true