kagu_homepage:
    path:     /dashboard
    defaults: { _controller: KaguBundle:Dashboard:index }

kagu_index_profil:
    path:   /profil/
    defaults: { _controller: KaguBundle:Profil:index }

kagu_index_ambiance:
    path:   /ambiance/
    defaults: { _controller: KaguBundle:Ambiance:index}

kagu_add_ambiance:
    path:    /ambiance/add
    defaults: { _controller: KaguBundle:Ambiance:add }

kagu_ambiance_ambiance:
    path:   /ambiance/ambiance/{ambiance}
    defaults: { _controller: KaguBundle:Ambiance:ambiance }

kagu_delete_ambiance:
    path:   /ambiance/delete/{ambiance}
    defaults: { _controller: KaguBundle:Ambiance:delete }

kagu_publish_ambiance:
    path:   /ambiance/publish/{ambiance}
    defaults: { _controller: KaguBundle:Ambiance:publish }

kagu_edit_ambiance:
    path:   /ambiance/edit/{ambiance}
    defaults: { _controller: KaguBundle:Ambiance:edit }

kagu_comment_ambiance:
    path:   /ambiance/id/{id}/comment/{comment}
    defaults: { _controller: KaguBundle:Ambiance:addComment }
    options:
        expose: true

kagu_add_item:
    path:   /ambiance/{ambiance}/add-item/
    defaults: { _controller: KaguBundle:Ambiance:addItem }